### ISSUE TITLE
The console supports synchronization of the latest schema

### ISSUE THREAD

**Issue by qwxingzhe** [apache/apisix-dashboard#1117]
# Feature request

## Please describe your feature

I hope the console can have the function of cleaning cache

## Describe the solution you'd like
When I was making a custom plug-in, I found that the list of console plug-ins was not updated after changing the configuration file of apimix. The FAQ mentioned using schema- sync.sh To update, but I was run by docker. I didn't find this file after entering the container through exec. This is very inconvenient. I hope the console has the function of synchronization, or the container service can automatically synchronize.

## Describe alternatives you've considered
1. Add synchronization button to the console
2. Restart the service and automatically synchronize the latest schema

**Comment by membphis** [comment]
@nic-chen @idbeta

**Comment by nic-chen** [comment]
good idea. welcome PR for this feature.

**Comment by qwxingzhe** [comment]
@nic-chen I'm going to finish it. Here's my idea:

1. Save the schema to etcd when APISIX restarts;
2. Where APISIX uses schema, it dynamically reads from etcd.

**Comment by nic-chen** [comment]
@qwxingzhe 
Thanks for your research!

We have discussed schema synchronization for a long time in the past few months and finally reached an agreement:

Instead of saving the schema to ETCD, export the schema in APISIX and copy it to the dashboard for use.

You can search to see related issues and maillist discussions.

If you could optimize base on the agreement, that would be great.
