### ISSUE TITLE
Dockerfile source code is COPY from the current version instead of remote download

### ISSUE THREAD

**Issue by hongbinhsu** [apache/apisix-dashboard#1182]
# dockerfile 源码从当前版本COPY而非远程下载

## 
docker build时，每次都需要远程下载文件，以及可能存在对应版本与分支版本不一致的情况

## Describe the solution you'd like
使用 COPY . /usr/local/apisix-dashboard 即可完成；即不用每次修改 dockerfile也节省了下载时间

## Describe alternatives you've considered

FROM golang:1.14 as api-builder
升级为
FROM golang:1.15 as api-builder

FROM node:14-alpine as fe-builder
升级为
FROM node:15-alpine as fe-builder

## Additional context

升级镜像，减少镜像层级

**Comment by juzhiyuan** [comment]
The Dockerfile under this repo would possibly be removed once we have published release images to Dockerhub.

**Comment by juzhiyuan** [comment]
The DockerHub maintains an image for Apache APISIX Dashboard[1], you could pull that image instead of the building by hand, and here is the issue[2] to track when to omit that Dockerfile.

[1] https://hub.docker.com/r/apache/apisix-dashboard
[2] https://github.com/apache/apisix-dashboard/issues/1265
