### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by chaosBreaking** [apache/apisix-dashboard#1183]
apisix-dashboard: v2.1分支
apisix: 2.1

问题

除了设置和监控两个tab以外的tab打开都显示Something went wrong. 错误内容是：Object(...) is not a function

**Comment by chaosBreaking** [comment]
![image](https://user-images.githubusercontent.com/23056897/103478363-205f9180-4e01-11eb-96ca-f367cadab5d2.png)

**Comment by juzhiyuan** [comment]
@chaosBreaking Hi, this issue is fixed in the v2.2 and later[1], could you have a try? 

BTW, we should maintain an LTS version indeed, so I just sent a mail[2], welcome to discuss with us. 

[1] https://apisix.apache.org/downloads/
[2] https://lists.apache.org/thread.html/r56c7ecc17ba06d4c1afc99cd9e823a12eaadc495030f99deb541c555%40%3Cdev.apisix.apache.org%3E
