### ISSUE TITLE
feat(fe): Press Enter key can trigger the Login button

### ISSUE THREAD

**Issue by imjoey** [apache/apisix-dashboard#1311]
# Feature request

## Please describe your feature

At login page, users have to explicitly click the `Login` button to do the login. It's common that also support for triggering login via pressing the `Enter` key. I believe this would be very convenient for those users who always use keyboard instead of mouse, like me. 😄 

## Describe the solution you'd like

After filling in the username and password fields, pressing the Enter key is able to make users do login.

**Comment by imjoey** [comment]
ping @juzhiyuan @liuxiran @nic-chen . If all accepted, this can be marked as good-first-issue. 😄

**Comment by juzhiyuan** [comment]
Of course

**Comment by nic-chen** [comment]
sure, that's great

**Comment by liuxiran** [comment]
LGTM ^_^

**Comment by yashi-hub** [comment]
hello, I'm Yashi Vijay. a sophomore undergraduate, INDIA. I'm a newbie at open source and would like to work on this task as a part of my outreachy contributions at APACHE.
is this issue still open? if yes, can you please provide me a minimum project setup guidance so that I can make my first PR at apache.  looking forward to it :) 
thank you.

**Comment by juzhiyuan** [comment]
ya, it's open, cc @LiteSun to guide u :)
