### ISSUE TITLE
Why we need to skip it in store not storage?

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#1357]
Why we need to skip it in store not storage?

_Originally posted by @ShiningRush in https://github.com/apache/apisix-dashboard/pull/1344#discussion_r562364607_

**Comment by imjoey** [comment]
After discussed with @ShiningRush at original issue, we decide to move the skip logic into Storage, instead of Store. This would make the Storage send `ONLY VALID` data to Store. Please refer to https://github.com/apache/apisix-dashboard/pull/1344#discussion_r562364607 for details. 

I would commit a PR to fix this soon.
