### ISSUE TITLE
how to delete the historical version of the APISIX node.

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix-dashboard#1482]
## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [e.g. 2.0-rc3]: dashboard 2.4

How to delete the extra historical version in the APISIX node? It prompts mismatch when deleting.

![image](https://user-images.githubusercontent.com/52862365/108456747-f4fb0e00-72ab-11eb-9fa5-2e991a177921.png)

**Comment by nic-chen** [comment]
Plugin `server-info` supports the expiration time of the specified information([refer](https://github.com/apache/apisix/blob/master/doc/plugins/server-info.md#how-to-customize-the-server-info-report-configurations)).


We could also support manual deletion of node data, what do you think?  @starsz @juzhiyuan

**Comment by starsz** [comment]
> Plugin `server-info` supports the expiration time of the specified information([refer](https://github.com/apache/apisix/blob/master/doc/plugins/server-info.md#how-to-customize-the-server-info-report-configurations)).
> 
> We could also support manual deletion of node data, what do you think? @starsz @juzhiyuan

Agree +1.

**Comment by nic-chen** [comment]
@bisakhmondal hi, could you help to fix this issue if you have time ?

**Comment by bisakhmondal** [comment]
Yeah definitely.

**Comment by nic-chen** [comment]
@bisakhmondal  
Thanks !
I think you could try to submit a proposal for this change  : )

**Comment by nic-chen** [comment]
@bisakhmondal 
Please deal with this issue first, it is a task in milestone 2.5, thanks.

**Comment by bisakhmondal** [comment]
Oh! I see. Then, I am going to look into it.
>We could also support manual deletion of node data, what do you think?

So this is the idea, right?

**Comment by nic-chen** [comment]
> Oh! I see. Then, I am going to look into it.
> 
> > We could also support manual deletion of node data, what do you think?
> 
> So this is the idea, right?

sure. that's it.

**Comment by LiteSun** [comment]
cc @guoqqqi to take a look.

**Comment by juzhiyuan** [comment]
Hi, after discuss with @nic-chen @starsz @LiteSun, we have a new way to support this feature.

How about only adding one extra message that tells users: `APISIX Node List will get updated in 2 hours by default.`, then we don't have necessary to remove nodes by hand & calling APIs.

**Comment by juzhiyuan** [comment]
If we support deleting nodes, it will take some other issues:

1. Where should we put the Delete button on this page?
2. Nodes in ETCD have the TTL option, it will expire in 2 hours by default, we don't have the necessary to delete it by hand.
3. If users delete nodes by mistake, they have to wait for APISIX to report its status, though it doesn't take a long time, users like me will get scared if we are not familiar with this logic (Only delete metrics from ETCD).

**Comment by nic-chen** [comment]
> Hi, after discuss with @nic-chen @starsz @LiteSun, we have a new way to support this feature.
> 
> How about only adding one extra message that tells users: `APISIX Node List will get updated in 2 hours by default.`, then we don't have necessary to remove nodes by hand & calling APIs.

OK

**Comment by bisakhmondal** [comment]
> Hi, after discuss with @nic-chen @starsz @LiteSun, we have a new way to support this feature.
> 
> How about only adding one extra message that tells users: `APISIX Node List will get updated in 2 hours by default.`, then we don't have necessary to remove nodes by hand & calling APIs.

Yeah, that's the default we have right now except for the displaying message part. We can definitely go for it. But looking at the current progress that has been made on this issue, I think it would be a better trade off to integrate the functionality since it'll help the pro peeps to have more customised & fine-grained control through the dashboard instead of waiting for 2 long hours.

Now coming to the implementation of the UI

>Where should we put the Delete button on this page?
>If users delete nodes by mistake, they have to wait for APISIX to report its status, though it doesn't take a long time, users like me will get scared if we are not familiar with this logic (Only delete metrics from ETCD).

I have prepared a mock-up for the same, which I think should address these concerns :)
The default screen:
![Screenshot from 2021-03-19 12-54-45](https://user-images.githubusercontent.com/41498427/111745364-7b5a3e00-88b2-11eb-870a-e19da17c133e.png)
On clicking the unlock, the user will be prompted with the necessary warnings.
![Screenshot from 2021-03-19 12-54-48](https://user-images.githubusercontent.com/41498427/111745413-8b721d80-88b2-11eb-8220-c9eb5d850473.png)
upon confirming to accept button, he/she will have fine-grained access.
![Screenshot from 2021-03-19 12-54-51](https://user-images.githubusercontent.com/41498427/111745513-b5c3db00-88b2-11eb-9018-a69f3193a921.png)

I have made the assets available on [google slides](https://docs.google.com/presentation/d/1Gmn-iLR66VO-YOrfmzBWlMsdOBfujigmJGY-fbv45Dc/edit?usp=sharing). Feel free to tinker with it & share your thoughts.

I think this omits the risk of unexpectedly deleting apisix node data by mistake. Let me know what you think. I'd be happy to address those. Thank you

**Comment by nic-chen** [comment]
@bisakhmondal  
Great! 
Thanks for sharing your thoughts.
I think we can discuss further.
But in version 2.5 we could prompt the user first.

**Comment by juzhiyuan** [comment]
Good design 👏 But I'm still concerned if we have necessary to add this API? let's wait for others :)

**Comment by juzhiyuan** [comment]
How about dropping this issue from M2.5? coz I'm still not sure if it's necessary to add this feature? 🤔

**Comment by juzhiyuan** [comment]
Let's wait for more replies

**Comment by juzhiyuan** [comment]
Due to these nodes will get dropped after some time, so close this issue
