### ISSUE TITLE
 plugin "proxy-rewrite" found in plugin-config detail page and not found in route detail page

### ISSUE THREAD

**Issue by xiaotaibai2008** [apache/apisix-dashboard#1719]
## Issue description
 plugin "proxy-rewrite" found in plugin-config detail page and not found in route detail page

## Expected behavior
 plugin "proxy-rewrite" both found or not found in plugin-config detail page and route detail page

## How to Reproduce

When creating the route, the "proxy-rewrite" plugin was not found ；

When creating the  plugin-config, the "proxy-rewrite" plugin was found ；

## Screenshots

![image](https://user-images.githubusercontent.com/24215735/114001827-e2a25700-988e-11eb-87ce-3f3e481729ff.png)

## Environment

![image](https://user-images.githubusercontent.com/24215735/114001886-f221a000-988e-11eb-8dc1-40bf259ea665.png)

**Comment by Abbila** [comment]
"Request Override" is the proxy-rewrite plugin  #1576

**Comment by juzhiyuan** [comment]
yes, this plugin is out of box.

**Comment by Abbila** [comment]
> yes, this plugin is out of box.
 I have a problem. I can search the rewrite plugin on the route view page，But I don't know it is a bug or a feature。

**Comment by juzhiyuan** [comment]
`Route View`? Could you please take a screenshot?

**Comment by liuxiran** [comment]
As we have removed the `proxy-rewrite` plugin out of step3 of `/routes/create` page, it should not be found in this page, after checking the latest code,  the current implementation  matched the expectation.

> I have a problem. I can search the rewrite plugin on the route view page，But I don't know it is a bug or a feature。

while checking this issue, I found that in the step2 of `/plugin-template/create` page, `proxy-rewrite` can still be found, that is not as expected, #1723 will fix this. So can this solve your problem @Abbila ?


> plugin "proxy-rewrite" both found or not found in plugin-config detail page and route detail page

`plugin-config detail page` means `/plugin/market` right @xiaotaibai2008 ? If so, IMHO `proxy-rewrite` can be found is as expected, because in this page, plugin is configured for the global, not only for the route, so just keep it in.

**Comment by Abbila** [comment]
@liuxiran @juzhiyuan When editing the route, proxy-rewrite can be found on the preview page of the route, which is the fourth step。
![image](https://user-images.githubusercontent.com/17827327/114123170-5e021800-9924-11eb-8123-0f79244b8e9f.png)

**Comment by liuxiran** [comment]
> @liuxiran @juzhiyuan When editing the route, proxy-rewrite can be found on the preview page of the route, which is the fourth step。

good catch @Abbila ~ there is a missing modification in https://github.com/apache/apisix-dashboard/blob/166137ea9fa42694f09beca3c5c19335b20abc6f/web/src/pages/Route/components/CreateStep4/CreateStep4.tsx#L62

**Comment by Engine-AI** [comment]
@liuxiran Already resolved in #1721 ，
