### ISSUE TITLE
 there is a problem with the yaml data format

### ISSUE THREAD

**Issue by Engine-AI** [apache/apisix-dashboard#1938]
## Issue description
In the data editor, when you select the data style yaml, click the format button, there is a problem with the yaml data format

## Screenshots

before format
![image](https://user-images.githubusercontent.com/17827327/121287675-94ecae00-c914-11eb-9d14-2d297e95e170.png)
after format
![image](https://user-images.githubusercontent.com/17827327/121287694-9fa74300-c914-11eb-9c3f-26cd8ee95a73.png)

**Comment by Engine-AI** [comment]
hi! @nic-chen @LiteSun @nic-chen ,When cyclically switching between json and yaml, and formatting, there is already a problem with the data.
![image](https://user-images.githubusercontent.com/17827327/121287943-1d6b4e80-c915-11eb-9477-93559af0c444.png)

**Comment by nic-chen** [comment]
@LiteSun  please help check, thanks.

**Comment by LiteSun** [comment]
ok

**Comment by liuxiran** [comment]
Since our  contributor has updated editor  to `monaco`, which is more powerful and will help your code style while editing, so we remove the `Format` function, hope this will solve your problem and improve your user experience ^^

Close issue now, you can reopen it if you have any questions, thanks @Engine-AI
