### ISSUE TITLE
Why can't I edit my plugin configuration in version 2.7

### ISSUE THREAD

**Issue by zengruzhen** [apache/apisix-dashboard#1950]
## Issue description
Plugin Editor Cannot enter

## Expected behavior
editor plugin config 

## How to Reproduce

1. Go to 'Create Route'
2. Go to 'Plugin Config'
3. Click on 'one of any plugin'
4. Try to edit
4. Cannot to edit

## Screenshots
![图片](https://user-images.githubusercontent.com/18514089/123024345-7e158380-d40b-11eb-8f42-09b72b2823ba.png)

## Environment

* apisix version (cmd: `apisix version`): 2.6
* OS (cmd: `uname -a`):4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.0
* apisix-dashboard version, if have:2.7
* Browser version, if have:Google Chrome 90.0.4430.72

## Additional context
I'm using the official image pulled from DockerHub

**Comment by zengruzhen** [comment]
![图片](https://user-images.githubusercontent.com/18514089/123028577-23cbf100-d412-11eb-8cc3-4b7820d64b53.png)

**Comment by zengruzhen** [comment]
I haven't encountered this problem in version 2.6.

**Comment by juzhiyuan** [comment]
Because Auth plugin doesn't need more configuration on the Route creator page.

![image](https://user-images.githubusercontent.com/2106987/123036706-1158b400-d420-11eb-9b76-0acb1cd570f1.png)

1. You need to configure it by creating a Consumer;
2. Then enable this plugin directly on the Route page.

**Comment by zengruzhen** [comment]
![图片](https://user-images.githubusercontent.com/18514089/123041105-72d05100-d427-11eb-97f1-40469e887724.png)
Well, I didn't use consumers in previous versions.
But why does this limit the use of the authz-keycloak plugin alone?But for example, using basic-auth alone can pass the front-end verification

**Comment by juzhiyuan** [comment]
I just checked the notification, it's from here https://github.com/apache/apisix-dashboard/blob/master/web/src/pages/Consumer/Create.tsx#L77-L80

FE will verify if this resource contains at leat one Auth plugin, it seems that there has something wrong, cc @liuxiran to take a look.

**Comment by liuxiran** [comment]
Sorry for late reply, we have already fixed a bug cased by the plugin type, see here: https://github.com/apache/apisix-dashboard/pull/1983

You can try to apply this patch to you code to fix this issue @zengruzhen, hope this will help you.

**Comment by liuxiran** [comment]
> ![图片](https://user-images.githubusercontent.com/18514089/123041105-72d05100-d427-11eb-97f1-40469e887724.png)
> Well, I didn't use consumers in previous versions.
> But why does this limit the use of the authz-keycloak plugin alone?But for example, using basic-auth alone can pass the front-end verification

This is because we need a `type=auth` plugin when create a Consumers, but for the `authz-keycloak` , type=other, so you will see this warning message. It is ok.

But We still need to do these things to make it more clearly for users:

* For `authz-keycloak` and `openid-connect` plugins, we need to:
![image](https://user-images.githubusercontent.com/2561857/126909108-f815844a-aa2b-42eb-ad67-7e1c01edef4c.png)
![image](https://user-images.githubusercontent.com/2561857/126909146-162d829d-b28a-4596-8eef-e0a970c4671c.png)

* update the warning tip about create/config Consumers, from `Please enable one authentication plugin` to `Please enable one of basic-auth, hmac-auth, jwt-auth, key-auth`, because `authz-keycloak` and `openid-connect` are also authentication plugins, but they have nothing to do with consumers.

![image](https://user-images.githubusercontent.com/2561857/126909214-c6b8b139-4b24-4a07-88b7-cb58de51f3dd.png)

cc @juzhiyuan @LiteSun
