### ISSUE TITLE
feat: dashboard supports selecting: Service Discovery when creating an upstream

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix-dashboard#1977]
# Feature request

Support the configuration of `discovery_type` and `service_name`.

**related issue** 

- https://github.com/apache/apisix-dashboard/issues/1911
- https://github.com/apache/apisix-dashboard/issues/1549

**Comment by juzhiyuan** [comment]
Just updated your first comment, and I will take this.

**Comment by liuxiran** [comment]
https://github.com/apache/apisix-dashboard/pull/1557

BE has already support this feature, remove `backend` tag

**Comment by liuxiran** [comment]
Refer to the https://apisix.apache.org/docs/apisix/2.7/discovery#supported-discovery-registries

In APISIX2.7 , we support Eureka/Consul/Nacos and service discovery via DNS,

in order to support this feature in dashboard, we have to update our `Upstream` module,  add `Target type` filed, user can choose `Node` or `Service Discovery`

when choose `Node`, user can complete the follow fields:
![image](https://user-images.githubusercontent.com/2561857/130003249-04101972-7660-4f01-8520-127a82b96574.png)

When choose `Service Discovery`, user can complete the following fields:
`discovery_type`, a list of `dns`、`consul_kv` `nacos` and `eureka`
`service_name `, input the your configured service name

It should be noted that, when `discovery_type` choose `nacos`, `discovery_args` can be configured, see: https://apisix.apache.org/docs/apisix/2.7/discovery/nacos#discovery_args for details.

cc @bzp2010 @juzhiyuan @Baoyuantop @tzssangglass @nic-chen @spacewander to help to check whether I missed some thing for this feature, thanks a lot.

**Comment by spacewander** [comment]
LGTM

**Comment by juzhiyuan** [comment]
LGTM

**Comment by nic-chen** [comment]
LGTM

**Comment by Baoyuantop** [comment]
LGTM

**Comment by bzp2010** [comment]
This issue is similar to issue #1989, and I will try it.
