### ISSUE TITLE
How to configure Service Discovery

### ISSUE THREAD

**Issue by zhengyuyzhao** [apache/apisix-dashboard#1989]
服务发现要怎么用dashboard配置

**Comment by tzssangglass** [comment]
You mean configure nacos, eureka? Not yet supported.

**Comment by zhengyuyzhao** [comment]
and zookeeper

**Comment by ericlinj** [comment]
and dns

**Comment by ericlinj** [comment]
i use api to config discovery service with discovery_type=dns，like this
```
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
		"name":"lg-api-route",
    "uri": "/*",
    "upstream": {
        "service_name": "lg-api.service.consul",
        "type": "roundrobin",
        "discovery_type": "dns"
    }
}'
```

but if i found ，after someone edit this route ，the value of discovery_type in upstream is missing
i think this is a bug！

**Comment by juzhiyuan** [comment]
> after someone edit this route ，the value of discovery_type in upstream is missing

Yes, because Dashboard doesn't support the Discovery now, so if you use Dashboard to edit a Route which is created by API directly, then the configuration will be overridden.

**Comment by ericlinj** [comment]
so
when can dashboard support this?
in prod
service discovery is sth necessary




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix-dashboard"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月3日(星期二) 中午11:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/apisix-dashboard] How to configure Service Discovery (#1989)





  
after someone edit this route ，the value of discovery_type in upstream is missing
  
Yes, because Dashboard doesn't support the Discovery now, so if you use Dashboard to edit a Route which is created by API directly, then the configuration will be overridden.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by juzhiyuan** [comment]
Once https://github.com/apache/apisix-dashboard/milestone/14 gets done, we will support Discovery in M2.7.2

**Comment by ericlinj** [comment]
expect it，thks a lot！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix-dashboard"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月3日(星期二) 中午11:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/apisix-dashboard] How to configure Service Discovery (#1989)





 
Once https://github.com/apache/apisix-dashboard/milestone/14 gets done, we will support Discovery in M2.7.2
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liuxiran** [comment]
Related issue：https://github.com/apache/apisix-dashboard/issues/1977

Just make sure that, once we supported `discovery_type` and `service_name` in dashboard, user only need two steps to use service discovery via APISIX Dashboard:

1. config service discovery in APISIX, see https://apisix.apache.org/docs/apisix/2.7/discovery/ for more configuration details,
2. create Upstream via dashboard

cc @tzssangglass @bzp2010 @nic-chen @spacewander to help check it , thanks a lot.

**Comment by nic-chen** [comment]
> Related issue：#1977
> 
> Just make sure that, once we supported `discovery_type` and `service_name` in dashboard, user only need two steps to use service discovery via APISIX Dashboard:
> 
> 1. config service discovery in APISIX, see [apisix.apache.org/docs/apisix/2.7/discovery](https://apisix.apache.org/docs/apisix/2.7/discovery/) for more configuration details,
> 2. create Upstream via dashboard
> 
> cc @tzssangglass @bzp2010 @nic-chen @spacewander to help check it , thanks a lot.

sure.

**Comment by bzp2010** [comment]
cc @liuxiran @nic-chen 
I have read the document. I will try it.

**Comment by liuxiran** [comment]
> cc @liuxiran @nic-chen
> I have read the document. I will try it.

Thanks very mush, and go a head boy~, any help please comment here

**Comment by liuxiran** [comment]
close by #2081

**Comment by sagarnaik965** [comment]
does dashboard supports discovery in apisix?
