### ISSUE TITLE
can not open consumer with numbers as name

### ISSUE THREAD

**Issue by hozaifaaoud** [apache/apisix-dashboard#2196]
### Issue description

The issue is that you can add a consumer through admin api and his name is 12345.
and if you go to the dashboard you will not be able to change any thing in this consumer configuration.
Here is a created user and I need to change something in its configuration
![image](https://user-images.githubusercontent.com/79872781/139914198-dddf54a0-362c-409d-b5b1-ac289b8fe3e6.png)

### Expected behavior

//

### How to Reproduce

//

### Environment

- apisix version (cmd: `apisix version`): 2.5
- OS (cmd: `uname -a`): linux ubuntu
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.9.1
- etcd version, if have (cmd: run `etcd --version`): 3.4.13
- apisix-dashboard version, if have: 2.6
- Browser version, if have:

### Additional context

//

**Comment by zaunist** [comment]
Hi, @hozaifaaoud, I checked this situation and reproduce this issue. It's occurred because APISIX support consumer name start with number, but APISIX-Dashboard does't support. Does the APISIX-Dashboard need to support consumer that start with number ? 

@juzhiyuan @nic-chen @starsz  Any suggestions?

![image](https://user-images.githubusercontent.com/38528079/144156333-85fb38a3-8d05-4d42-a3e6-8950898155f1.png)

**Comment by nic-chen** [comment]
we should keep the same with APISIX.

**Comment by juzhiyuan** [comment]
@zaunist Please see https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L693 , may need to keep the regex the same as apisix.

**Comment by zaunist** [comment]
> @zaunist Please see https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L693 , may need to keep the regex the same as apisix.

Fine，I am glad to make contribution for this issue.
