### ISSUE TITLE
bug: Dashboard, "Submit" on Plugins does not work, JS error: Error: strict mode: unknown keyword: "encrypt_fields" 

### ISSUE THREAD

**Issue by Charckle** [apache/apisix-dashboard#2855]
### Resolved
After troubleshooting, it was a corrupted schema.json that was the problem. Not entirely sure why, but reverting to the default one worked. We switched from loki to elastic search, so the modified schema is no longer needed.

### Current Behavior

When adding some plugins, expl: elasticsearch in the global rules, or key-auth and others when creating a consumer, Dashboard is unable to add them, due to a javascript error: Uncaught (in promise) Error: strict mode: unknown keyword: "encrypt_fields"

There is no problem adding plugins via http requests.

### Expected Behavior

Dashboard should execute the command and activate the plugin, prompting the user that "Configure Plugin Successfully"

### Error Logs

p__Plugin__List.86b10e9e.async.js:1 Uncaught (in promise) Error: strict mode: unknown keyword: "encrypt_fields"
    at Object.ce [as checkStrictMode] (p__Plugin__List.86b10e9e.async.js:1:1112851)
    at Object.O [as checkUnknownRules] (p__Plugin__List.86b10e9e.async.js:1:1408625)
    at ee (p__Plugin__List.86b10e9e.async.js:1:1111250)
    at Object.z [as validateFunctionCode] (p__Plugin__List.86b10e9e.async.js:1:1109032)
    at n.v (p__Plugin__List.86b10e9e.async.js:1:1912128)
    at n.value (p__Plugin__List.86b10e9e.async.js:1:4559499)
    at n.value (p__Plugin__List.86b10e9e.async.js:1:4551822)
    at p__Plugin__List.86b10e9e.async.js:1:3484393
    at new Promise (<anonymous>)
    at p__Plugin__List.86b10e9e.async.js:1:3484139

### Steps to Reproduce

1. Run Apisix via docker
2. Add a consumer
3. Enable "key-auth" on the consumer

### Environment

- APISIX version: 3.4.0
- APISIX Dashboard version: 3.0.1
- APISIX Dashboard image: apache/apisix-dashboard:3.0.1-alpine

**Comment by Charckle** [comment]
The issue can be closed, the problem was a corrupted schema.json.

**Comment by dgpratikpatil** [comment]
How was the corrupted schema.json fixed?

I have generated schema.json from `GET /v1/schema` api but still I'm getting the same error.

Dashboard version 3.0.0
Deploy source: docker image 3.0.0 alpine
APISIX version: 3.8.0

**Comment by TravarA** [comment]
This is still a problem.

### Environment

-   APISIX version: 3.9.0
-   APISIX Dashboard version: 3.0.1
-   APISIX Dashboard image: apache/apisix-dashboard:latest

I needed to use the `loki-logger` plugin so I had to update the Dashboard's `schema.json`, because the plugin wasn't available (along with `body-transformer` and a few others) in the dashboard.

After the update, I was able to use the plugin, however, trying to use the `openid-connect` plugin, I'd get the error from the OP.

The only way to use both plugins, was to modify the `schema.json` and remove the `"encrypt_fields"` property from the `openid-connect` plugin.

**Comment by jzhao20230918** [comment]
the dashboard does not support the keyword "encrypt_fields"
