### ISSUE TITLE
How to update admin_key?

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#403]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
How to update admin_key or API key?
___
### Bug
- Which version of Apache APISIX Dashboard, OS and Broswer?
1.5

- What happened?
If possible, provide a way to reproduce the error.
![image](https://user-images.githubusercontent.com/2106987/91143860-c2e66600-e6e5-11ea-9c88-a5f4dcc70437.png)
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
After this issue is resolved, we may update the README

**Comment by laopaz** [comment]
![image](https://user-images.githubusercontent.com/59036981/91145328-dbf01680-e6e7-11ea-83bf-2a0a4db2a5d0.png)
I also encounter this problem. After modifying the token, 401 error will appear on the dashboard page

**Comment by gxthrj** [comment]
This is because manager-api needs to specify `admin-key` when accessing apisix.
the config file is https://github.com/apache/apisix-dashboard/blob/master/api/conf/conf_preview.json#L16, 
and you can modify the key through environment named `APISIX_API_KEY`,
we will get the value from env before start manager-api (https://github.com/apache/apisix-dashboard/blob/master/api/build.sh#L27)
