### ISSUE TITLE
An error is reported when creating the second route：RouteGroup name is duplicate 

### ISSUE THREAD

**Issue by y934317258** [apache/apisix-dashboard#452]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
master
- What happened?
RouteGroup name is duplicate 
![image](https://user-images.githubusercontent.com/68832358/92431455-27b3bd00-f1ca-11ea-8448-b55f29286859.png)

If possible, provide a way to reproduce the error.
An error is reported when creating the second route
___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
@liuxiran Please take a look, thanks!

**Comment by y934317258** [comment]
![J86ZQR1`7F4(VG` 085D @L](https://user-images.githubusercontent.com/68832358/92442453-7ec58c00-f1e2-11ea-903a-40281f4229fc.jpg)
Maybe it's the problem here. I'm not sure

**Comment by liuxiran** [comment]
@y934317258 yes this error is due to the front ends corresponding to the routeGroup are still not merged
when creating a route, a group without a name is created by default. When a new route is created, a new group (with no name) is created by default. Two groups without a same name report this error.

it'll be solved with the routegroup pr merged and we will update the logic at the same time . Thank you~

**Comment by juzhiyuan** [comment]
merged, feel free to reopen this one.
