### ISSUE TITLE
Proposal: Full lifecycle API management 

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-dashboard#611]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [ ] Requirements
- [x] Feature or performance improvement
- [ ] Other

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.

TODO

**Comment by liuxiran** [comment]
### Refactor features
1. Publish and offline route.
as discussed before, we could add a `status` field for route on APISIX,  so If the solution remains the same, dashboard will add this function  after apIsIx has added it. 

1. route online debug.
we plan to use the previous implementation, import `react-swagger-ui`. Based on the original implementation, we will suppley the authentication and parameter verification part, so that the route online debug will  become more complete and easy to use. 
Besides, we will add a new feature to generate apisdk, which would make it easy for users to dock the api published on the gateway

### The feature to discuss

1. For create route, we propose to add Import the export feature. import a route from openapi configuration, and export the route configuration compatible with openapi. It will be easier for the apis written with openapi specification to access the gateway.

1. For publish route, we propose to introduce the concept of a publishing environment, e.g: test environment and Production environment. When a user publishes a route, they can choose the publishing environment. The benefit is that it makes it easy for users to adapt a set of routing designs to different operating environments, but at the same time, it introduces the burden of publishing environmental management.

1. Permission control of the resource.  Permission control of resources depends on user management, I wonder if we have plan to add this moudle.


cc @juzhiyuan @nic-chen @membphis @moonming

**Comment by membphis** [comment]
it is nice for me ^_^

**Comment by moonming** [comment]
>     3\. Permission control of the resource.  Permission control of resources depends on user management, I wonder if we have plan to add this moudle.

do you means RBAC?

**Comment by liuxiran** [comment]
> > ```
> > 3\. Permission control of the resource.  Permission control of resources depends on user management, I wonder if we have plan to add this moudle.
> > ```
> 
> do you means RBAC?

Yep, and this is also a feature that enterprise users need ☺️

**Comment by LiteSun** [comment]
Additional feature to discuss:
1. Monitor Routes
2. Alarm Mechanism
3. Version management of route

Technical details will be discussed in the corresponding proposal.

**Comment by juzhiyuan** [comment]
This tracker issue could be closed.
